// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IAlertLanguageMessageFields {
  /** Internal name */
  internalName: string;

  /** Message */
  message: string;

  /** CTA */
  cta: IExternalNavigationLink | IInternalNavigationLink;
}

export interface IAlertLanguageMessage
  extends Entry<IAlertLanguageMessageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'alertLanguageMessage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IArticleFields {
  article: any;
  /** Internal Name */
  internalName: string;

  /** Image */
  image?: Asset | undefined;

  /** Title */
  title: string;

  /** Sub-Title */
  subTitle?: string | undefined;

  /** Post Meta */
  postMeta?: string | undefined;

  /** Content */
  content: Document;

  /** Published Date */
  publishedDate: string;

  /** Author */
  author?: IAuthor | undefined;

  /** Category */
  category: IArticleCategory;

  /** Topic */
  topic: IArticleTopic[];

  /** Channel */
  channel: IArticleChannel;

  /** Preview Content */
  previewContent?: string | undefined;

  /** Secondary preview image */
  secondaryPreviewImage?: Asset | undefined;

  /** Is Featured Article */
  isFeaturedArticle: boolean;

  /** Hide From Lists */
  hideFromLists: boolean;

  /** Override Link */
  overrideLink?: IExternalNavigationLink | IInternalNavigationLink | undefined;
}

export type OverrideLinkOptions =
  | IExternalNavigationLink
  | IInternalNavigationLink
  | undefined;

type OverrideLinkOptionsValues = 'external' | 'internal';
// export type OverrideLinkOptions = typeof OverrideLinkOptionsValues;

export interface IArticle extends Entry<IArticleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'article';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IArticleCategoryFields {
  /** Internal Name */
  internalName: string;

  /** Display Title */
  displayTitle: string;
}

export interface IArticleCategory extends Entry<IArticleCategoryFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'articleCategory';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IArticleChannelFields {
  /** Internal Name */
  internalName: string;

  /** Display Title */
  displayTitle: string;
}

export interface IArticleChannel extends Entry<IArticleChannelFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'articleChannel';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IArticleTopicFields {
  /** Internal Name */
  internalName: string;

  /** Display Title */
  displayTitle: string;
}

export interface IArticleTopic extends Entry<IArticleTopicFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'articleTopic';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IAuthorFields {
  /** Internal Name */
  internalName: string;

  /** Photo */
  photo?: Asset | undefined;

  /** Full Name */
  fullName: string;

  /** First Name */
  firstName: string;

  /** Last Name */
  lastName: string;
}

export interface IAuthor extends Entry<IAuthorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'author';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IAwardItemFields {
  /** Internal Name */
  internalName: string;

  /** Images */
  images: Asset[];

  /** Title */
  title: string;
}

export interface IAwardItem extends Entry<IAwardItemFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'awardItem';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IBrandblockStatsFields {
  /** Internal name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Title */
  title: string;

  /** Content */
  content: string;

  /** dataSupText */
  dataSupText?: string | undefined;
}

export interface IBrandblockStats extends Entry<IBrandblockStatsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'brandblockStats';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IDictionaryLookupFields {
  /** Internal Name */
  internalName: string;

  /** Dictionary Text */
  dictionaryText: string;
}

export interface IDictionaryLookup extends Entry<IDictionaryLookupFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'dictionaryLookup';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IExternalNavigationLinkFields {
  /** Internal Name */
  internalName: string;

  /** Display Title */
  displayTitle: string;

  /** CSS */
  css?: string | undefined;

  /** External Link */
  externalLink: string;

  /** Target */
  target?: '_blank' | '_self' | '_parent' | '_top' | undefined;

  /** Icon Link */
  iconLink?: IIcon | undefined;

  /** Preview Title */
  previewTitle?: string | undefined;

  /** Preview Content */
  previewContent?: string | undefined;

  /** Preview Image */
  previewImage?: Asset | undefined;

  /** Secondary preview image */
  secondaryPreviewImage?: Asset | undefined;
}

/** Navigation Link used to link to External sites/pages. */

export interface IExternalNavigationLink
  extends Entry<IExternalNavigationLinkFields> {
  externalLink: string | undefined;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'externalNavigationLink';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IFooterConfigurationFields {
  /** Internal Name */
  internalName: string;

  /** Logo */
  logo: Asset;

  /** Right Image */
  rightImage?: Asset | undefined;

  /** Links */
  links: (IExternalNavigationLink | IInternalNavigationLink)[];

  /** Copyright */
  copyright?: Document | undefined;

  /** Blocks */
  blocks?: (IUiHtmlContent | IUiRawHtml)[] | undefined;

  /** Social Links */
  socialLinks?: IExternalNavigationLink[] | undefined;

  /** Main Menu */
  mainMenu: IUiMenu;
}

export interface IFooterConfiguration
  extends Entry<IFooterConfigurationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'footerConfiguration';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IHeaderConfigurationFields {
  /** Internal Name */
  internalName: string;

  /** Logo */
  logo: Asset;

  /** Utility Navigation */
  utilityNavigation?:
    | (IExternalNavigationLink | IInternalNavigationLink)[]
    | undefined;

  /** Utility Navigation CTA */
  utilityNavigationCta?:
    | IExternalNavigationLink
    | IInternalNavigationLink
    | undefined;

  /** Main Menu */
  mainMenu: IUiMenu;

  /** Languages */
  languages: ILanguage[];

  /** New Main Menu */
  newMainMenu: IUiMegaMenu;
}

export interface IHeaderConfiguration
  extends Entry<IHeaderConfigurationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'headerConfiguration';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IIconFields {
  /** Internal Name */
  internalName: string;

  /** Icon */
  icon: string;
}

export interface IIcon extends Entry<IIconFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'icon';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IIndustryReportListItemFields {
  /** Internal Name */
  internalName: string;

  /** Title */
  title: string;

  /** Text */
  text?: string | undefined;
}

export interface IIndustryReportListItem
  extends Entry<IIndustryReportListItemFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'industryReportListItem';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IInternalNameFields {
  /** Internal Name */
  internalName: string;

  /** Display Title */
  displayTitle: Document;

  /** Content */
  content: Document;

  /** Icon Link */
  iconLink?: IIcon | undefined;
}

export interface IInternalName extends Entry<IInternalNameFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'internalName';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IInternalNavigationLinkFields {
  /** Internal Name */
  internalName: string;

  /** Display Title */
  displayTitle: string;

  /** CSS */
  css?: string | undefined;

  /** Querystring */
  querystring?: string | undefined;

  /** Internal Link */
  internalLink: IUiPage;

  /** Target */
  target?: '_blank' | '_self' | '_parent' | '_top' | undefined;
}

/** Navigation Link used to link to internal pages. */

export interface IInternalNavigationLink
  extends Entry<IInternalNavigationLinkFields> {
  internalLink: any;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'internalNavigationLink';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILanguageFields {
  /** Internal Name */
  internalName: string;

  /** Display Title */
  displayTitle: string;

  /** Language Code */
  languageCode?: 'en' | 'fr' | 'de' | 'es' | 'pt' | undefined;
}

export interface ILanguage extends Entry<ILanguageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'language';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILinkProductContentFields {
  /** Internal name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Cta */
  cta: IInternalNavigationLink;

  /** subCta */
  subCta?: (IExternalNavigationLink | IInternalNavigationLink)[] | undefined;
}

export interface ILinkProductContent extends Entry<ILinkProductContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'linkProductContent';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILocationItemFields {
  /** Internal Name */
  internalName: string;

  /** Location Name */
  locationName: string;

  /** Address */
  address: Document;
}

export interface ILocationItem extends Entry<ILocationItemFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'locationItem';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISeoFields {
  /** Internal Name */
  internalName: string;

  /** Twitter Site */
  twitterSite?: string | undefined;

  /** Twitter Creator */
  twitterCreator?: string | undefined;

  /** Default Twitter Image */
  defaultTwitterImage?: Asset | undefined;

  /** Default Facebook Image */
  defaultFacebookImage?: Asset | undefined;

  /** Robots TXT */
  robotsTxt?: string | undefined;

  /** twitter:Card */
  twittercard?: string | undefined;
}

/** Seo configuration */

export interface ISeo extends Entry<ISeoFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'seo';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISeoMetadataFields {
  /** Internal Name */
  internalName: string;

  /** Meta Title */
  metaTitle: string;

  /** Meta Description */
  metaDescription: string;

  /** Canonical Url */
  canonicalUrl?: string | undefined;

  /** No Index */
  noIndex?: boolean | undefined;

  /** No Follow */
  noFollow?: boolean | undefined;

  /** og:Image */
  ogimage?: Asset | undefined;

  /** og:Type */
  ogtype?: string | undefined;

  /** OG Title */
  ogTitle?: string | undefined;

  /** OG Description */
  ogDescription?: string | undefined;

  /** max-snippet */
  maxSnippet?: string | undefined;

  /** max-video */
  maxVideo?: string | undefined;

  /** max-image */
  maxImage?: string | undefined;

  /** Exclude from Sitemap */
  excludeFromSitemap?: boolean | undefined;

  /** twitter:Image */
  twitterimage?: Asset | undefined;

  /** Twitter Title */
  twitterTitle?: string | undefined;

  /** Twitter Card */
  twitterCard?: string | undefined;

  /** Twitter Site */
  twitterSite?: string | undefined;

  /** Twitter Creator */
  twitterCreator?: string | undefined;

  /** Twitter Description */
  twitterDescription?: string | undefined;
}

export interface ISeoMetadata extends Entry<ISeoMetadataFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'seoMetadata';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISiteConfigurationFields {
  /** Internal Name */
  internalName: string;

  /** Site URL */
  siteUrl: string;

  /** Header Configuration */
  headerConfiguration: IHeaderConfiguration;

  /** Awards Configuration */
  awardsConfiguration?: IUiAwards | undefined;

  /** Footer Configuration */
  footerConfiguration: IFooterConfiguration;

  /** SEO Configuration */
  seoConfiguration: ISeo;

  /** Language alert message */
  languageAlertMessage?: IAlertLanguageMessage | undefined;
}

export interface ISiteConfiguration extends Entry<ISiteConfigurationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'siteConfiguration';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ITeamMemberFields {
  /** Internal Name */
  internalName: string;

  /** Image */
  image: Asset;

  /** Image is rounded */
  isRounded: boolean;

  /** Name */
  name: string;

  /** Role */
  role: string;

  /** Bio */
  bio: string;

  /** Social Links */
  socialLinks: IExternalNavigationLink[];

  /** CTA text */
  ctaText?: string | undefined;

  /** CTA link */
  ctaLink?: string | undefined;
}

export interface ITeamMember extends Entry<ITeamMemberFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'teamMember';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ITestimonialFields {
  /** Internal Name */
  internalName: string;

  /** Photo */
  photo: Asset;

  /** Quote */
  quote: Document;

  /** Person Name */
  personName: string;

  /** Designation */
  designation: string;

  /** Company */
  company: string;

  /** Company Logo */
  companyLogo: Asset;

  /** Story Link */
  storyLink: IExternalNavigationLink | IInternalNavigationLink;
}

export interface ITestimonial extends Entry<ITestimonialFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'testimonial';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiAnimatedBannerFields {
  /** Internal name */
  internalName: string;

  /** Title */
  title?: Document | undefined;

  /** Subtitle */
  subtitle?: Document | undefined;

  /** Headline Left */
  headlineLeft: Document;

  /** Headline Right */
  headlineRight: Document;

  /** Image */
  image?: Asset | undefined;

  /** Animation type */
  animationType: 'pull' | 'push';

  /** Banner type */
  bannerType?: 'poster' | 'underlap' | undefined;

  /** Button type */
  buttonType?: 'scroll' | 'primary' | 'secondary' | 'passive' | undefined;

  /** CTA */
  cta?: IExternalNavigationLink | IInternalNavigationLink | undefined;
}

export interface IUiAnimatedBanner extends Entry<IUiAnimatedBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiAnimatedBanner';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiArticleFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Article */
  article: IArticle;
}

export interface IUiArticle extends Entry<IUiArticleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiArticle';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiArticleBannerFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Mobile Image */
  mobileImage: Asset;

  /** Desktop Image */
  desktopImage: Asset;

  /** Quote */
  quote: string;

  /** Quote By */
  quoteBy: string;

  /** Designation */
  designation: string;

  /** Company */
  company: string;

  /** Social Links */
  socialLinks?: IExternalNavigationLink[] | undefined;
}

export interface IUiArticleBanner extends Entry<IUiArticleBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiArticleBanner';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiArticleCallToActionFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Image */
  image: Asset;

  /** Title */
  title: string;

  /** Content */
  content: Document;

  /** CTA */
  cta: IExternalNavigationLink | IInternalNavigationLink;
}

export interface IUiArticleCallToAction
  extends Entry<IUiArticleCallToActionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiArticleCallToAction';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiArticleListFields {
  /** Internal Name */
  title?: string | undefined;

  /** Heading main */
  headingMain?: string | undefined;

  /** Featured Article */
  featuredArticle?: IUiPage | undefined;

  /** Blue Theme */
  blueTheme: boolean;

  /** Articles Per Page */
  articlesPerPage: number;

  /** */
  imageSize: string;

  /** */
  imageObjectFit: string;
}

export interface IUiArticleList extends Entry<IUiArticleListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiArticleList';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiArticleQuoteFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Quote */
  quote: string;

  /** Company */
  company: string;

  /** By */
  by: string;
}

export interface IUiArticleQuote extends Entry<IUiArticleQuoteFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiArticleQuote';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiAwardsFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Title */
  title: Document;

  /** Award Items */
  awardItems: IAwardItem[];
}

export interface IUiAwards extends Entry<IUiAwardsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiAwards';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiBrandBlockFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Display Title */
  displayTitle: Document;

  /** Content */
  content: string;

  /** Image */
  image: Asset;

  /** Background Image */
  backgroundImage: Asset;
}

export interface IUiBrandBlock extends Entry<IUiBrandBlockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiBrandBlock';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiBrandLogosFields {
  /** Internal name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Title */
  title: string;

  /** Images */
  images: Asset[];
}

export interface IUiBrandLogos extends Entry<IUiBrandLogosFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiBrandLogos';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiCampaignBannerFields {
  /** Internal name */
  internalName: string;

  /** Background color */
  backgroundColor?: string | undefined;

  /** Title */
  title?: Document | undefined;

  /** Title color */
  titleColor?: string | undefined;

  /** Subtitle color */
  subtitleColor?: string | undefined;

  /** Subtitle */
  subtitle?: Document | undefined;

  /** Perex color */
  perexColor?: string | undefined;

  /** Perex */
  perex?: Document | undefined;

  /** Headline Top */
  headlineTop: Document;

  /** Image */
  image: Asset;

  /** Mobile Image */
  mobileImage: Asset;
}

export interface IUiCampaignBanner extends Entry<IUiCampaignBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiCampaignBanner';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiCardFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Display Title */
  displayTitle: Document;

  /** Card Content */
  cardContent: Document;

  /** Image */
  image: Asset;

  /** Blue Background Color */
  blueBackgroundColor: boolean;

  /** Right Icon Link */
  rightIconLink?: IIcon | undefined;
}

export interface IUiCard extends Entry<IUiCardFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiCard';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiCardAdvancedFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Background color */
  backgroundColor?: string | undefined;

  /** Display Title */
  displayTitle: Document;

  /** Card Content */
  cardContent: Document;

  /** Image */
  image?: Asset | undefined;

  /** Blue Background Color */
  blueBackgroundColor?: boolean | undefined;

  /** Right Icon Link */
  rightIconLink?: IIcon | undefined;

  /** Background Image */
  backgroundImage?: Asset | undefined;

  /** Cta */
  cta?: IExternalNavigationLink | IInternalNavigationLink | undefined;

  /** Cta type */
  ctaType?:
    | 'Primary'
    | 'Secondary'
    | 'PassiveAlt'
    | 'ProductPrimary'
    | 'ProductSecondary'
    | 'ProductPassiveAlt'
    | 'HeaderPrimary'
    | 'CardAlt'
    | undefined;
}

export interface IUiCardAdvanced extends Entry<IUiCardAdvancedFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiCardAdvanced';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiContactBannerFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Title */
  title: string;

  /** Content */
  content: string;

  /** Image */
  image: Asset;

  /** Align Left */
  alignLeft: boolean;

  /** Form */
  form: IUiRawHtml;

  /** Display Title */
  displayTitle: Document;
}

export interface IUiContactBanner extends Entry<IUiContactBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiContactBanner';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiCxIndexBannerFields {
  /** Internal Name */
  internalName: string;

  /** Content */
  content: Document;
}

export interface IUiCxIndexBanner extends Entry<IUiCxIndexBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiCxIndexBanner';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface jsonModelFields {
  /** Internal Name */
  internalName: string;
  componentName: string;
  data: any;
}

export interface IJsonModel extends Entry<jsonModelFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'jsonModel';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiEmbeddedFormFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** TitleCss */
  titleCss?: string | undefined;

  /** Sub Title */
  subTitle?: string | undefined;

  /** SubTitleCss */
  subTitleCss?: string | undefined;

  /** Type */
  type: 'default' | 'alt' | 'article';

  /** Raw Form Embed */
  rawFormEmbed: IUiRawHtml;

  /** Background Color */
  backgroundColor?: string | undefined;

  /** Background Size */
  backgroundSize?: string | undefined;

  /** Background Position */
  backgroundPosition?: string | undefined;

  /** Background Type */
  backgroundType?: 'poster' | 'solid';

  /** Image */
  image?: Asset | undefined;

  /** Mobile Image */
  mobileImage?: Asset | undefined;

  /** CRM URL */
  crmUrl?: string | undefined;

  /** Form ID */
  formId: string;

  /** Form Style */
  formStyle?: 'light' | 'dark';

  /** MunchkinId */
  munchkinId?: string | undefined;

  /** Two Column */
  twoColumns?: boolean;
}

export interface IUiEmbeddedForm extends Entry<IUiEmbeddedFormFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiEmbeddedForm';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiFeatureGroupFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Title */
  title?: Document | undefined;

  /** Features */
  features: IInternalName[];

  /** Type */
  type?: 'campaign' | undefined;
}

export interface IUiFeatureGroup extends Entry<IUiFeatureGroupFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiFeatureGroup';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiGroupedBrandBlockFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Three Icon Paragraph */
  threeIconParagraph: IUiThreeIconParagraph;

  /** Brand Block */
  brandBlock: IUiBrandBlock;
}

export interface IUiGroupedBrandBlock
  extends Entry<IUiGroupedBrandBlockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiGroupedBrandBlock';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiHeroFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Image */
  image: Asset;

  /** Title */
  title: Document;

  /** Sub Title */
  subTitle?: Document | undefined;

  /** Content */
  content?: Document | undefined;

  /** CTA */
  cta?: IExternalNavigationLink | IInternalNavigationLink | undefined;

  /** CTA Type */
  ctaType?:
    | 'Primary'
    | 'Secondary'
    | 'PassiveAlt'
    | 'ProductPrimary'
    | 'ProductSecondary'
    | 'ProductPassiveAlt'
    | 'HeaderPrimary'
    | 'LoadMore'
    | undefined;

  /** Align Text Left */
  alignTextLeft: boolean;
}

export interface IUiHero extends Entry<IUiHeroFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiHero';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiHeroAdvancedFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Image */
  image: Asset;

  /** Mobile Image */
  mobileImage: Asset;

  /** Background color */
  backgroundColor?: string | undefined;

  /** Title */
  title: Document;

  /** Title Color */
  titleColor?: string | undefined;

  /** Sub Title */
  subTitle?: Document | undefined;

  /** subTitleColor */
  subTitleColor?: string | undefined;

  /** Content */
  content?: Document | undefined;

  /** CTA */
  cta?: IExternalNavigationLink | IInternalNavigationLink | undefined;

  /** CTA Type */
  ctaType?:
    | 'Primary'
    | 'Secondary'
    | 'PassiveAlt'
    | 'ProductPrimary'
    | 'ProductSecondary'
    | 'ProductPassiveAlt'
    | 'HeaderPrimary'
    | 'LoadMore'
    | undefined;

  /** Align Text Left */
  alignTextLeft: boolean;

  /** OptionalCTA */
  optionalCta?: IExternalNavigationLink | IInternalNavigationLink | undefined;

  /** Optional CTA Type */
  optionalCtaType?:
    | 'Primary'
    | 'Secondary'
    | 'PassiveAlt'
    | 'ProductPrimary'
    | 'ProductSecondary'
    | 'ProductPassiveAlt'
    | 'HeaderPrimary'
    | undefined;

  /** Theme */
  theme:
    | 'dark-blue'
    | 'light-gray'
    | 'light-blue'
    | 'dark-gray'
    | 'medium-blue'
    | 'medium-purple';

  /** Orientation */
  orientation: 'right' | 'left';

  /** Banner type */
  bannerType?: 'poster' | undefined;
}

export interface IUiHeroAdvanced extends Entry<IUiHeroAdvancedFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiHeroAdvanced';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiHeroAreaFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Mobile Image */
  mobileImage: Asset;

  /** Desktop Image */
  desktopImage: Asset;

  /** Title */
  title: string;

  /** Content */
  content: string;

  /** Alight Text Left */
  alightTextLeft: boolean;

  /** CTA */
  cta: IExternalNavigationLink | IInternalNavigationLink;

  /** CTA Type */
  ctaType:
    | 'Primary'
    | 'Secondary'
    | 'PassiveAlt'
    | 'ProductPrimary'
    | 'ProductSecondary'
    | 'ProductPassiveAlt'
    | 'HeaderPrimary'
    | 'LoadMore';

  /** Default Hero Type */
  defaultHeroType: boolean;

  /** Type */
  type?: 'campaign' | undefined;
}

export interface IUiHeroArea extends Entry<IUiHeroAreaFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiHeroArea';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiHtmlContentFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** HTML */
  html: Document;
}

export interface IUiHtmlContent extends Entry<IUiHtmlContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiHtmlContent';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiIconLinksFields {
  /** Internal name */
  internalName: string;

  /** Title */
  title?: string | undefined;

  /** Links */
  links: (IExternalNavigationLink | IInternalNavigationLink)[];
}

export interface IUiIconLinks extends Entry<IUiIconLinksFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiIconLinks';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiIndustryReportsPageFields {
  /** Internal Name */
  internalName: string;

  /** Hero banner content */
  heroBannerContent: Document;

  /** Hero banner bullet points list */
  heroBannerBulletPointsList: IIndustryReportListItem[];

  /** Hero Banner img */
  heroBannerImg: Asset;
}

export interface IUiIndustryReportsPage
  extends Entry<IUiIndustryReportsPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiIndustryReportsPage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiInternalLinkSideImageFields {
  /** Internal name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Image */
  image: Asset;

  /** Link */
  link: IExternalNavigationLink | IInternalNavigationLink;
}

export interface IUiInternalLinkSideImage
  extends Entry<IUiInternalLinkSideImageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiInternalLinkSideImage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiLinkProductsFields {
  /** Internal name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Color */
  color?: string | undefined;

  /** Links */
  links: ILinkProductContent;
}

export interface IUiLinkProducts extends Entry<IUiLinkProductsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiLinkProducts';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiLocationsFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Location Title */
  locationTitle: string;

  /** Locations */
  locations: ILocationItem[];
}

export interface IUiLocations extends Entry<IUiLocationsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiLocations';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiMediaNavigationLinkFields {
  /** Internal Name */
  internalName: string;

  /** Display Title */
  displayTitle: string;

  /** CSS */
  css?: string | undefined;

  /** Querystring */
  querystring?: string | undefined;

  /** Target */
  target?: '_blank' | '_self' | '_parent' | '_top' | undefined;

  /** Media */
  media: Asset;
}

/** Navigation Link used to link to internal pages. */

export interface IUiMediaNavigationLink
  extends Entry<IUiMediaNavigationLinkFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiMediaNavigationLink';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiMegaMenuFields {
  /** Internal Name */
  internalName: string;

  /** Sub Menus */
  subMenus: IUiMegaMenuSubMenu[];
}

export interface IUiMegaMenu extends Entry<IUiMegaMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiMegaMenu';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiMegaMenuColumnFields {
  /** Column Title */
  columnTitle: string;

  /** Thumbnail */
  thumbnail?: Asset | undefined;

  /** Abstract */
  abstract?: string | undefined;

  /** Column Title Link */
  columnTitleLink?:
    | IExternalNavigationLink
    | IInternalNavigationLink
    | undefined;

  /** Background Color */
  backgroundColor?:
    | 'Cornflower Dark Blue'
    | 'Dark Blue'
    | 'Dark Gray'
    | 'Light Gray'
    | 'Purple'
    | 'Subtle Blue'
    | 'Subtle Dark Blue'
    | 'Subtle Purple'
    | undefined;

  /** Link List */
  linkList?: (IExternalNavigationLink | IInternalNavigationLink)[] | undefined;

  /** Date */
  date?: string | undefined;

  /** Hide Date */
  hideDate: boolean;
}

export interface IUiMegaMenuColumn extends Entry<IUiMegaMenuColumnFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiMegaMenuColumn';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiMegaMenuSubMenuFields {
  /** Navigation Title */
  navigationTitle?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** Abstract */
  abstract?: string | undefined;

  /** CTA Link */
  ctaLink: IExternalNavigationLink | IInternalNavigationLink;

  /** Sub Menu Columns */
  subMenuColumns: IUiMegaMenuColumn[];

  /** Learn More Text */
  learnMoreText: string;
}

export interface IUiMegaMenuSubMenu extends Entry<IUiMegaMenuSubMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiMegaMenuSubMenu';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiMenuFields {
  /** Internal Name */
  internalName: string;

  /** Sub Menus */
  subMenus: (IUiSubMenu | IExternalNavigationLink | IInternalNavigationLink)[];
}

export interface IUiMenu extends Entry<IUiMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiMenu';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiMenuColumnFields {
  /** Internal Name */
  internalName: string;

  /** Display Title */
  displayTitle?: string | undefined;

  /** Links */
  links: (
    | IUiInternalLinkSideImage
    | IUiLinkProducts
    | IExternalNavigationLink
    | IInternalNavigationLink
  )[];

  /** Type */
  type?: 'Default' | 'Link side image' | 'Link card' | 'Products' | undefined;
}

export interface IUiMenuColumn extends Entry<IUiMenuColumnFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiMenuColumn';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiPageFields {
  /** Internal Name */
  internalName: string;

  /** Title */
  title: string;

  /** Slug */
  slug: string;

  /** Blocks */
  blocks: (
    | IArticle
    | IUiAnimatedBanner
    | IUiArticle
    | IUiArticleBanner
    | IUiArticleCallToAction
    | IUiArticleList
    | IUiArticleQuote
    | IUiAwards
    | IUiBrandLogos
    | IUiBrandBlock
    | IUiCampaignBanner
    | IUiContactBanner
    | IUiCxIndexBanner
    | IUiEmbeddedForm
    | IUiGroupedBrandBlock
    | IUiHtmlContent
    | IUiIconLinks
    | IUiIndustryReportsPage
    | IUiLocations
    | IUiPageContent
    | IUiPageListing
    | IUiPageListingNotDynamic
    | IUiPreFooterCta
    | IUiProductHeader
    | IUiQuoteBlock
    | IUiRawHtml
    | IUiResourceCardGroup
    | IUiResourceFeatureCard
    | IUiResourceFeaturedPost
    | IUiResourceList2ColumnRow
    | IUiResourceList3ColumnRow
    | IUiSearchResults
    | IUiShortBanner
    | IUiStatistic
    | IUiStatsblock
    | IUiTeamMembers
    | IUiTestimonials
    | IUiThreeCardGroup
    | IUiThreeIconParagraph
    | IUiTrialForm
    | IUiTrialPageGrid
    | IUiFeatureGroup
    | IUiHero
    | IUiHeroAdvanced
    | IUiHeroArea
    | IUiProductBanner
    | IUiSecondaryContentArea
    | IJsonModel
  )[];

  /** SEO */
  seo: ISeoMetadata;

  /** Page Path */
  pagePath?: string | undefined;

  /** Do Not Index Internal Search */
  doNotIndexInternalSearch?: boolean | undefined;

  /** Is Article */
  isArticle: boolean;

  /** Is Simplified */
  isSimplified?: boolean | undefined;

  /** isAwardsHidden */
  isAwardsHidden?: boolean | undefined;
}

/** Use UI Page to create any page. */

export interface IUiPage extends Entry<IUiPageFields> {
  seo: any;
  isArticle: any;
  blocks: any;
  pagePath: string;
  slug: any;
  title: any;
  content: any;
  doNotIndexInternalSearch: any;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiPage';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiPageContentFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Article */
  article: IArticle | IUiIndustryReportsPage;
}

export interface IUiPageContent extends Entry<IUiPageContentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiPageContent';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiPageListingFields {
  /** Internal name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** Css */
  css?: string | undefined;

  /** CssBackground color */
  cssBackgroundColor?: string | undefined;

  /** Number of Page items */
  numberOfPageItems: number;

  /** Pages path type */
  pagePath: string;

  /** Type */
  type: 'customer stories' | 'resources';

  /** Card Title */
  cardTitle: string;
}

/** Listing of pages like blogs, resources, etc. */

export interface IUiPageListing extends Entry<IUiPageListingFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiPageListing';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiPageListingNotDynamicFields {
  /** Internal name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Title */
  title?: string | undefined;

  /** Css */
  css?: string | undefined;

  /** Background color */
  backgroundColor?: string | undefined;

  /** Card Content */
  cardContent: (IExternalNavigationLink | IInternalNavigationLink)[];

  /** Type */
  type: 'customer stories' | 'resources';

  /** Center content (Resources) */
  centerContentResources?: boolean | undefined;

  /** Component type */
  componentType?: 'campaign' | undefined;
}

export interface IUiPageListingNotDynamic
  extends Entry<IUiPageListingNotDynamicFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiPageListingNotDynamic';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiPreFooterCtaFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Title */
  title: string;

  /** Content */
  content: string;

  /** CTA */
  cta: IExternalNavigationLink | IInternalNavigationLink;

  /** CTA Type */
  ctaType?:
    | 'Primary'
    | 'Secondary'
    | 'PassiveAlt'
    | 'ProductPrimary'
    | 'ProductSecondary'
    | 'ProductPassiveAlt'
    | 'HeaderPrimary'
    | undefined;
}

export interface IUiPreFooterCta extends Entry<IUiPreFooterCtaFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiPreFooterCta';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiProductBannerFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Image */
  image: Asset;

  /** Title */
  title: Document;

  /** Content */
  content?: Document | undefined;

  /** CTA */
  cta?: IExternalNavigationLink | IInternalNavigationLink | undefined;

  /** CTA Type */
  ctaType?:
    | 'Primary'
    | 'Secondary'
    | 'PassiveAlt'
    | 'ProductPrimary'
    | 'ProductSecondary'
    | 'ProductPassiveAlt'
    | 'HeaderPrimary'
    | 'LoadMore'
    | undefined;

  /** Align Text Left */
  alignTextLeft: boolean;
}

export interface IUiProductBanner extends Entry<IUiProductBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiProductBanner';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiProductHeaderFields {
  /** Internal Name */
  internalName: string;

  /** Logo */
  logo: Asset;

  /** Anchor Links */
  anchorLinks: IExternalNavigationLink[];
}

export interface IUiProductHeader extends Entry<IUiProductHeaderFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiProductHeader';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiQuoteBlockFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Type */
  type: string;

  /** Quote */
  quote: string;

  /** Quote By */
  quoteBy: string;

  /** */
  quoteByColor?: string;

  /** */
  headlineColor?: string;

  /** Company Name */
  companyName: string;

  /** */
  companyNameColor?: string;

  /** */
  role?: string;

  /** */
  roleColor?: string;

  /** */
  backgroundColor?: string;

  /** */
  backgroundPosition?: string;

  /** */
  backgroundSize?: 'cover' | 'contain' | 'fill' | 'none';

  /** */
  orientation?: 'left' | 'center' | 'right';

  /** Background Image */
  backgroundImage: Asset;

  /** Logo Images */
  logoImages: Asset[];

  /** CTA */
  cta:
    | IExternalNavigationLink
    | IInternalNavigationLink
    | IUiMediaNavigationLink;

  /** CTA Type */
  ctaType?:
    | 'Primary'
    | 'OutlinePrimary'
    | 'Secondary'
    | 'PassiveAlt'
    | 'ProductPrimary'
    | 'ProductSecondary'
    | 'ProductPassiveAlt'
    | 'HeaderPrimary'
    | 'LoadMore'
    | undefined;
}

export interface IUiQuoteBlock extends Entry<IUiQuoteBlockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiQuoteBlock';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiRawHtmlFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Raw HTML */
  rawHtml: string;
}

export interface IUiRawHtml extends Entry<IUiRawHtmlFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiRawHtml';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiResourceCardFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Display Title */
  displayTitle: Document;

  /** Sub Title */
  subTitle?: string | undefined;

  /** Content */
  content: string;

  /** CTA */
  cta?: IExternalNavigationLink | IInternalNavigationLink | undefined;

  /** Image */
  image?: Asset | undefined;

  /** CTA Type */
  ctaType?:
    | 'Primary'
    | 'Secondary'
    | 'PassiveAlt'
    | 'ProductPrimary'
    | 'ProductSecondary'
    | 'ProductPassiveAlt'
    | 'HeaderPrimary'
    | 'LoadMore'
    | 'ResourceCardButton'
    | undefined;
}

export interface IUiResourceCard extends Entry<IUiResourceCardFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiResourceCard';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiResourceCardGroupFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Resource Cards */
  resourceCards: IUiResourceCard[];
}

export interface IUiResourceCardGroup
  extends Entry<IUiResourceCardGroupFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiResourceCardGroup';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiResourceFeatureCardFields {
  /** Internal Title */
  internalTitle: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Photo Label */
  photoLabel?: string | undefined;

  /** Display Title */
  displayTitle: Document;

  /** Sub-Title */
  subTitle?: string | undefined;

  /** Content */
  content: string;

  /** Mobile Image */
  mobileImage: Asset;

  /** Desktop Image */
  desktopImage: Asset;

  /** CTA */
  cta: IExternalNavigationLink | IInternalNavigationLink;

  /** Variation */
  variation: '1' | '2';

  /** Position */
  position: 'top' | 'left' | 'right';
}

export interface IUiResourceFeatureCard
  extends Entry<IUiResourceFeatureCardFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiResourceFeatureCard';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiResourceFeaturedPostFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Photo Label */
  photoLabel?: string | undefined;

  /** Mobile Image */
  mobileImage: Asset;

  /** Desktop Image */
  desktopImage: Asset;

  /** Display Title */
  displayTitle: Document;

  /** Sub-Title */
  subTitle?: string | undefined;

  /** Content */
  content: string;

  /** CTA */
  cta: IExternalNavigationLink | IInternalNavigationLink;
}

export interface IUiResourceFeaturedPost
  extends Entry<IUiResourceFeaturedPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiResourceFeaturedPost';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiResourceList2ColumnRowFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Column Cards */
  columnCards: (IUiResourceCard | IUiResourceFeatureCard)[];
}

export interface IUiResourceList2ColumnRow
  extends Entry<IUiResourceList2ColumnRowFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiResourceList2ColumnRow';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiResourceList3ColumnRowFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** 3 Column Cards */
  columnCards: IUiResourceCardGroup;
}

export interface IUiResourceList3ColumnRow
  extends Entry<IUiResourceList3ColumnRowFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiResourceList3ColumnRow';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiSearchResultsFields {
  /** Internal Name */
  internalName?: string | undefined;

  /** Results Per Page */
  resultsPerPage: number;

  /** No Results Title */
  noResultsTitle: string;

  /** No results Text */
  noResultsText: string;
}

export interface IUiSearchResults extends Entry<IUiSearchResultsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiSearchResults';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiSecondaryContentAreaFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Title */
  title: string;

  /** Content */
  content: Document;

  /** Mobile Image */
  mobileImage: Asset;

  /** Desktop Image */
  desktopImage: Asset;

  /** CTA */
  cta?: IExternalNavigationLink | IInternalNavigationLink | undefined;

  /** CTA Type */
  ctaType?:
    | 'Primary'
    | 'Secondary'
    | 'PassiveAlt'
    | 'ProductPrimary'
    | 'ProductSecondary'
    | 'ProductPassiveAlt'
    | 'HeaderPrimary'
    | 'LoadMore'
    | undefined;
}

export interface IUiSecondaryContentArea
  extends Entry<IUiSecondaryContentAreaFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiSecondaryContentArea';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiShortBannerFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Type */
  type: 'Resource' | 'Executive' | 'Articles' | 'campaign';

  /** Display Title */
  displayTitle: Document;

  /** Content */
  content?: string | undefined;

  /** Display Content */
  displayContent?: string | undefined;

  /** Image */
  image?: Asset | undefined;

  /** CTA */
  cta?: IExternalNavigationLink | IInternalNavigationLink | undefined;
}

export interface IUiShortBanner extends Entry<IUiShortBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiShortBanner';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiStatisticFields {
  /** Internal name */
  internalName: string;

  /** Description */
  description?: Document | undefined;

  /** Number */
  number: number;

  /** Unit key */
  unitKey?: 'percent' | 'usd' | undefined;

  /** Unit placement */
  unitPlacement: 'right' | 'left';
}

export interface IUiStatistic extends Entry<IUiStatisticFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiStatistic';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiStatsblockFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Display Title */
  displayTitle: Document;

  /** TitleColor */
  titleColor?: string | undefined;

  /** Content */
  content?: string | undefined;

  /** Image */
  image?: Asset | undefined;

  /** Background Image */
  backgroundImage?: Asset | undefined;

  /** Background color */
  backgroundColor?: string | undefined;

  /** Statsfields */
  statsfields?: IBrandblockStats[] | undefined;
}

export interface IUiStatsblock extends Entry<IUiStatsblockFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiStatsblock';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiSubMenuFields {
  /** Internal Name */
  internalName: string;

  /** Link Above Title */
  linkAboveTitle?: IInternalNavigationLink | undefined;

  /** Display Title */
  displayTitle?: string | undefined;

  /** Menu Columns */
  menuColumns: IUiMenuColumn[];

  /** Link */
  link?: IExternalNavigationLink | IInternalNavigationLink | undefined;
}

export interface IUiSubMenu extends Entry<IUiSubMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiSubMenu';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiTeamMembersFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Column layout */
  isColumnLayout: boolean;

  /** Team Members */
  teamMembers: ITeamMember[];
}

export interface IUiTeamMembers extends Entry<IUiTeamMembersFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiTeamMembers';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiTestimonialsFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Testimonials */
  testimonials: ITestimonial[];
}

export interface IUiTestimonials extends Entry<IUiTestimonialsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiTestimonials';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiThreeCardGroupFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Cards */
  cards: (IUiCard | IUiCardAdvanced)[];

  /** Title */
  title?: Document | undefined;
}

export interface IUiThreeCardGroup extends Entry<IUiThreeCardGroupFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiThreeCardGroup';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiThreeIconParagraphFields {
  /** Internal Name */
  internalName: string;

  /** Anchor Id */
  anchorId?: string | undefined;

  /** Display Title */
  displayTitle: Document;

  /** Content */
  content: string;

  /** Icon Link 1 */
  iconLink1: IIcon;

  /** Icon 1 Sub-Title */
  icon1SubTitle: string;

  /** Icon Link 2 */
  iconLink2: IIcon;

  /** Icon Link 3 */
  iconLink3: IIcon;

  /** Icon 3 Sub-Title */
  icon3SubTitle: string;

  /** Three Card Group */
  threeCardGroup?: IUiThreeCardGroup | undefined;
}

export interface IUiThreeIconParagraph
  extends Entry<IUiThreeIconParagraphFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiThreeIconParagraph';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiTrialFormFields {
  /** Internal Name */
  internalName: string;

  /** Heading */
  heading: string;

  /** Bullet points list */
  bulletPointsList: Document;

  /** Images */
  images: Asset[];

  /** First Name Label */
  firstName: string;

  /** Last Name Label */
  lastName: string;

  /** Phone Number Label */
  phoneNumber: string;

  /** Email Label */
  email: string;

  /** Company Label */
  company: string;

  /** Country Label */
  country?: string | undefined;

  /** Job Function Label */
  jobFunction?: string | undefined;

  /** Job Level Label */
  jobLevel?: string | undefined;

  /** Number of Employees Label */
  numberOfEmployees?: string | undefined;

  /** Industry Label */
  industry: string;

  /** Password Label */
  password: string;

  /** Consent */
  consent: string;

  /** Privacy Policy */
  privacyPolicy: Document;

  /** Submit button text */
  submitButtonText: string;

  /** Login link */
  loginLink: string;

  /** Log In */
  loginText: string;

  /** ResultBlockSuccessTitle */
  resultBlockSuccessTitle: string;

  /** ResultBlockSuccessText */
  resultBlockSuccessText: Document;

  /** ResultBlockFailTitle */
  resultBlockFailTitle: string;
}

export interface IUiTrialForm extends Entry<IUiTrialFormFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiTrialForm';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IUiTrialPageGridFields {
  /** Internal Name */
  internalName: string;

  /** Heading Left */
  headingLeft?: string | undefined;

  /** Description Left */
  descriptionLeft?: Document | undefined;

  /** Bullet points list column left */
  bulletPointsListColLeft?: Document | undefined;

  /** CTA text left */
  ctaTextLeft?: string | undefined;

  /** CTA link left */
  ctaLinkLeft?: string | undefined;

  /** Notice */
  notice?: string | undefined;

  /** Tag Recommended */
  tagRecommended?: string | undefined;

  /** Heading Right */
  headingRight?: string | undefined;

  /** Description Right */
  descriptionRight?: Document | undefined;

  /** Bullet points list column right */
  bulletPointsListColRight?: Document | undefined;

  /** CTA text right */
  ctaTextRight?: string | undefined;

  /** CTA link right */
  ctaLinkRight?: string | undefined;

  /** CTA banner */
  ctaBanner?: Document | undefined;

  /** Table Data JSON */
  tableData?: Record<string, any> | undefined;

  /** Stripe banner */
  stripeBanner?: Document | undefined;

  /** Stripe banner - button text */
  stripeBannerButtonText?: string | undefined;

  /** Stripe banner - button link */
  stripeBannerButtonLink?: string | undefined;
}

export interface IUiTrialPageGrid extends Entry<IUiTrialPageGridFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'uiTrialPageGrid';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE =
  | 'alertLanguageMessage'
  | 'article'
  | 'articleCategory'
  | 'articleChannel'
  | 'articleTopic'
  | 'author'
  | 'awardItem'
  | 'brandblockStats'
  | 'dictionaryLookup'
  | 'externalNavigationLink'
  | 'footerConfiguration'
  | 'headerConfiguration'
  | 'icon'
  | 'industryReportListItem'
  | 'internalName'
  | 'internalNavigationLink'
  | 'language'
  | 'linkProductContent'
  | 'locationItem'
  | 'seo'
  | 'seoMetadata'
  | 'siteConfiguration'
  | 'teamMember'
  | 'testimonial'
  | 'uiAnimatedBanner'
  | 'uiArticle'
  | 'uiArticleBanner'
  | 'uiArticleCallToAction'
  | 'uiArticleList'
  | 'uiArticleQuote'
  | 'uiAwards'
  | 'uiBrandBlock'
  | 'uiBrandLogos'
  | 'uiCampaignBanner'
  | 'uiCard'
  | 'uiCardAdvanced'
  | 'uiContactBanner'
  | 'uiCxIndexBanner'
  | 'uiEmbeddedForm'
  | 'uiFeatureGroup'
  | 'uiGroupedBrandBlock'
  | 'uiHero'
  | 'uiHeroAdvanced'
  | 'uiHeroArea'
  | 'uiHtmlContent'
  | 'uiIconLinks'
  | 'uiIndustryReportsPage'
  | 'uiInternalLinkSideImage'
  | 'uiLinkProducts'
  | 'uiLocations'
  | 'uiMediaNavigationLink'
  | 'uiMegaMenu'
  | 'uiMegaMenuColumn'
  | 'uiMegaMenuSubMenu'
  | 'uiMenu'
  | 'uiMenuColumn'
  | 'uiPage'
  | 'uiPageContent'
  | 'uiPageListing'
  | 'uiPageListingNotDynamic'
  | 'uiPreFooterCta'
  | 'uiProductBanner'
  | 'uiProductHeader'
  | 'uiQuoteBlock'
  | 'uiRawHtml'
  | 'uiResourceCard'
  | 'uiResourceCardGroup'
  | 'uiResourceFeatureCard'
  | 'uiResourceFeaturedPost'
  | 'uiResourceList2ColumnRow'
  | 'uiResourceList3ColumnRow'
  | 'uiSearchResults'
  | 'uiSecondaryContentArea'
  | 'uiShortBanner'
  | 'uiStatistic'
  | 'uiStatsblock'
  | 'uiSubMenu'
  | 'uiTeamMembers'
  | 'uiTestimonials'
  | 'uiThreeCardGroup'
  | 'uiThreeIconParagraph'
  | 'uiTrialForm'
  | 'uiTrialPageGrid'
  | 'jsonModel';

export type LOCALE_CODE = 'de' | 'en' | 'es' | 'fr' | 'pt';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en';
